packs:
  - 'https://github.com/luamod1337/2take1packs/blob/master/config/Kasimaso.2take1pack?raw=true'
  - 'https://github.com/luamod1337/2take1packs/blob/master/config/packList.yml?raw=true'
  - 'https://github.com/luamod1337/2take1packs/blob/master/config/t0xicc0ma.2take1pack?raw=true'
